[workspace]

members = [
    "d01",
    "d02",
    "d03",
    "d04",
    "d05",
    "d06",
    "d07",
    "d08",
    "d10",
    "d11",
    "d13",
    "d14",
    "d15",
    "d16",
    "d17",
    "utils",
]
resolver = "2"

# [workspace.dependencies]
